### PR TITLE
Added stun damage tracking

### PR DESCRIPTION
**Pull request by flaming910**
Added a new column that users can opt into that keeps track of stun damage dealt

### CODE REVIEW

**Comment by coavins** [comment]
Hey thanks for the PR! I can take a look this evening.

**Comment by flaming910** [comment]
I need to fix the tests at some point but thats abt it

**Comment by coavins** [comment]
I'm working on a refactor for this to make addDamageToBoss way less tedious to call.

**Comment by coavins** [comment]
This looks good now, sorry for the force push! I'm going to test this a bit and merge it tonight.

**Pull request merged**
